#!/usr/bin/env python3
"""Regenerates the effect list in README.md from the registry.

The list is whatever the host simulator reports, so it cannot drift from the
code. Build the simulator first, then run this from the repository root:

    cmake -S tools/sim -B tools/sim/build -G Ninja
    cmake --build tools/sim/build
    python tools/gen_readme_effects.py

Pass --check to fail instead of writing, which is what CI wants.
"""

from __future__ import annotations

import argparse
import os
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
BEGIN = "<!-- BEGIN EFFECT LIST (generated by tools/gen_readme_effects.py) -->"
END = "<!-- END EFFECT LIST -->"

# What each group id holds, for the heading above its table.
GROUP_TITLES = {
    "1d_a": "1D, batch A",
    "1d_b": "1D, batch B",
    "1d_c": "1D, batch C",
    "1d_d": "1D, batch D",
    "1d_e": "1D, batch E",
    "1d2d": "Native 1D and 2D",
    "2d_a": "2D, batch A",
    "2d_b": "2D, batch B",
    "audio_vol": "Audio reactive, volume",
    "audio_fft": "Audio reactive, FFT",
    "audio_particle": "Audio reactive, particle",
    "particle_1d": "Particle, 1D",
    "particle_2d": "Particle, 2D",
    "mm": "WLED-MM exclusives",
}

FLAG_0D = 1 << 0
FLAG_1D = 1 << 1
FLAG_2D = 1 << 2
FLAG_VOLUME = 1 << 3
FLAG_FFT = 1 << 4

LINE = re.compile(r"^(\S+)\s+(.+?)\s+flags=0x([0-9A-Fa-f]{2})\s")


def find_sim() -> pathlib.Path:
    # WLED_FX_SIM names a build somewhere else, which is how the WSL wrapper
    # points this at the Linux build instead of a stale Windows .exe that WSL
    # would otherwise run through binfmt interop. See tools/wsl/sim.sh.
    if override := os.environ.get("WLED_FX_SIM"):
        candidate = pathlib.Path(override)
        if not candidate.exists():
            sys.exit(f"WLED_FX_SIM names {candidate}, which does not exist")
        return candidate
    for name in ("wled_fx_sim", "wled_fx_sim.exe"):
        candidate = ROOT / "tools" / "sim" / "build" / name
        if candidate.exists():
            return candidate
    sys.exit("build the simulator first: cmake --build tools/sim/build")


def dimensions(flags: int) -> str:
    bits = []
    if flags & FLAG_1D:
        bits.append("1D")
    if flags & FLAG_2D:
        bits.append("2D")
    if flags & FLAG_VOLUME:
        bits.append("volume")
    if flags & FLAG_FFT:
        bits.append("FFT")
    return ", ".join(bits) if bits else "1D"


def render() -> str:
    out = subprocess.run(
        [str(find_sim()), "--list"], capture_output=True, text=True, check=True
    ).stdout
    groups: dict[str, list[tuple[str, int]]] = {}
    total = 0
    for line in out.splitlines():
        match = LINE.match(line)
        if match is None:
            continue
        group, name, flags = match.group(1), match.group(2).strip(), int(match.group(3), 16)
        groups.setdefault(group, []).append((name, flags))
        total += 1

    offered_1d = sum(1 for e in groups.values() for _, f in e if f & (FLAG_1D | FLAG_0D))
    offered_2d = sum(1 for e in groups.values() for _, f in e if f & FLAG_2D)
    lines = [
        BEGIN,
        "",
        f"{total} effects are registered. Names are the WLED display names and they are "
        "what an `effects:` allow-list, the `effect:` option and the `select` entity all use.",
        "",
        f"Which of them an output offers depends on its shape: **{offered_1d} on a 1D "
        f"output** and **{offered_2d} on a 2D output**, or all {total} on a 2D output "
        "that sets `include_1d_effects: true`. The \"Runs on\" column below is what "
        "decides that; see [Which effects an output offers](#which-effects-an-output-offers).",
        "",
    ]
    for group in sorted(groups, key=lambda g: (GROUP_TITLES.get(g, ""), g)):
        entries = groups[group]
        lines.append(f"**{GROUP_TITLES.get(group, group)}** (`{group}`, {len(entries)})")
        lines.append("")
        lines.append("| Effect | Runs on |")
        lines.append("|---|---|")
        for name, flags in entries:
            lines.append(f"| {name} | {dimensions(flags)} |")
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if README is stale")
    args = parser.parse_args()

    text = README.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        sys.exit(f"README.md is missing the {BEGIN} / {END} markers")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    updated = head + render() + tail

    if args.check:
        if updated != text:
            sys.exit("README effect list is stale, run tools/gen_readme_effects.py")
        print("README effect list is current")
        return 0
    README.write_text(updated, encoding="utf-8")
    print("README effect list regenerated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
